
device: {
  name: cuda, 
  device_id: 1,           # select the second H100 (the first is used by Guido)
  deterministic: true,    # Ensure deterministic behavior (useful for reproducibility)
  benchmark: true,        # Enable cudnn auto-tuner to find the best algorithm to use for my hardware
}

dataset: {
    train : { _base_: cfgs/dataset_cfgs/occlusion/graph_folds_occluded.yaml,
            use_distance_edges: False, 
            use_hierarchy_edges: True
            },
    test : { _base_: cfgs/dataset_cfgs/occlusion/graph_test_occluded.yaml,
            use_distance_edges: False, 
            use_hierarchy_edges: True
            },
}

optimizer: {
  lr: 0.001, #0.005,
}

model: {
  NAME: GNN,
  gnn_input_channels: 384,
  gnn_hidden_channels: 64,
  classes: 22,
  heads: 6,
  heads_final_conv: 4,
  dropout: 0.5, 
  depth: 2, 
  noise_percentage: 0
}

dataset_percentage: 100
batch_size: 128
epochs: 1000
labels: /srv/healthcare/datascience/data/part-net/data_table/all_unique_integer_label_pairs.csv 
wandb_project: Occlusion